In [1]:
from pandas import read_csv
import pandas as pd
import numpy as np

In [2]:
data = read_csv('./database_5min.csv')
data.head()

,DateTime_start,DateTime_end,Scenario,Sequence,Plant,Leaf,DateTime_start_sequence,DateTime_end_sequence,DateTime_end_CO2_in,CO2_outflux_umol_s,...,Tr_mean_leaf,g0_mean_leaf,g1_mean_leaf,VcMaxRef_mean_plant,JMaxRef_mean_plant,RdRef_mean_plant,TPURef_mean_plant,Tr_mean_plant,g0_mean_plant,g1_mean_plant
0,2021-03-09T00:08:30.0,2021-03-09T00:13:30.0,400ppm,3,3,6.0,2021-03-08T16:25:00.0,2021-03-11T15:39:29.0,2021-03-09T00:13:30.0,-0.308024,...,25.0,0.011071,1.552607,40.865913,82.25748,0.576463,5.920633,25.0,0.012323,1.428968
1,2021-03-09T00:08:30.0,2021-03-09T00:13:30.0,400ppm,3,3,7.0,2021-03-08T16:25:00.0,2021-03-11T15:39:29.0,2021-03-09T00:13:30.0,-0.308024,...,25.0,0.011071,1.552607,40.865913,82.25748,0.576463,5.920633,25.0,0.012323,1.428968
2,2021-03-09T00:08:30.0,2021-03-09T00:13:30.0,400ppm,3,3,3.0,2021-03-08T16:25:00.0,2021-03-11T15:39:29.0,2021-03-09T00:13:30.0,-0.308024,...,25.0,0.011071,1.552607,40.865913,82.25748,0.576463,5.920633,25.0,0.012323,1.428968
3,2021-03-09T00:08:30.0,2021-03-09T00:13:30.0,400ppm,3,3,5.0,2021-03-08T16:25:00.0,2021-03-11T15:39:29.0,2021-03-09T00:13:30.0,-0.308024,...,25.0,0.011071,1.552607,40.865913,82.25748,0.576463,5.920633,25.0,0.012323,1.428968
4,2021-03-09T00:18:30.0,2021-03-09T00:23:30.0,400ppm,3,3,6.0,2021-03-08T16:25:00.0,2021-03-11T15:39:29.0,2021-03-09T00:23:30.0,-0.303082,...,25.0,0.011071,1.552607,40.865913,82.25748,0.576463,5.920633,25.0,0.012323,1.428968

In [3]:
#how many DateTime_start's are there
data['DateTime_start']

0        2021-03-09T00:08:30.0
1        2021-03-09T00:08:30.0
2        2021-03-09T00:08:30.0
3        2021-03-09T00:08:30.0
4        2021-03-09T00:18:30.0
                 ...
37444    2021-03-18T14:51:30.0
37445    2021-03-23T05:38:30.0
37446    2021-03-23T06:48:30.0
37447    2021-03-23T09:17:30.0
37448    2021-03-23T10:27:30.0
Name: DateTime_start, Length: 37449, dtype: str

In [4]:
df_agg = (data
    .groupby('DateTime_start')
    .agg({
        'Ta_measurement': 'mean', # 기온
        'Rh_measurement': 'mean', # 습도
        'R_measurement': 'mean', # 광량
        'CO2_ppm': 'mean', #이산화탄소 농도
        'Tl_mean': 'mean'
    })
    .dropna(subset=['Tl_mean'])
    .copy())

df_agg.columns = ['Ta', 'Rh', 'R', 'CO2', 'Tl']
df_agg = df_agg.reset_index()

In [5]:
df_agg.shape

(6028, 6)

In [6]:
df_agg.head()

,DateTime_start,Ta,Rh,R,CO2,Tl
0,2021-03-09T00:08:30.0,22.536364,80.363636,0.000000,416.272727,25.836832
1,2021-03-09T00:18:30.0,22.600000,79.563636,0.000000,416.909091,26.256781
2,2021-03-09T00:28:30.0,22.618182,80.581818,0.000000,415.818182,25.955940
3,2021-03-09T00:38:30.0,22.700000,79.018182,0.000000,416.090909,25.710634
4,2021-03-09T00:48:30.0,22.663636,79.954545,0.000000,415.909091,25.644834
...,...,...,...,...,...,...
6023,2021-05-03T06:24:30.0,24.827273,80.109091,21.545455,803.000000,26.015491
6024,2021-05-03T06:34:30.0,25.127273,80.081818,35.363636,799.909091,26.106932
6025,2021-05-03T06:44:30.0,25.427273,79.663636,49.272727,794.454545,25.983900
6026,2021-05-03T06:54:30.0,25.663636,79.800000,61.636364,790.272727,25.960147
6027,2021-05-03T07:04:30.0,25.800000,79.554545,76.090909,728.909091,25.986803

In [7]:
df_agg.to_csv("agg.csv")

In [31]:
#if we need something more

df_sorted = (df_agg
    .set_index('DateTime_start')
    .sort_index())
df_sorted.index = pd.to_datetime(df_sorted.index)
df_resampled = (df_sorted
    .resample('10min')
    .mean()
    .interpolate())